name: Deploy Terraform Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
  CONTAINER_NAME: tfstate
  ENVIRONMENTS: dev pre pro

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discover resources
        id: set-resources
        run: |
          RESOURCES=$(find . -maxdepth 1 -type d -not -path '.' -not -path './.*' -exec basename {} \; | jq -R . | jq -s . -c)
          echo "resources=$RESOURCES" >> $GITHUB_OUTPUT

  deploy-resources:
    needs: discover-resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Deploy Terraform for each resource and environment

        run: |
          RESOURCES='${{ needs.discover-resources.outputs.resources }}'
          echo "Resources JSON: $RESOURCES"
          for RESOURCE in $(echo "$RESOURCES" | jq -r '.[]'); do
            for ENV in $ENVIRONMENTS; do
              echo "Deploying $RESOURCE in $ENV..."
              cd "$RESOURCE/$ENV"

              cd ../..
            done
          done