name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  TF_VERSION: '1.0.0'
  TF_WORKING_DIR: '${{ github.event.inputs.environment }}'

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest



    defaults:
      run:
        working-directory: if(${{ inputs.environment == 'development' }}, 'dev', if(${{ inputs.environment == 'staging' }}, 'pre', 'pro'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: directory
        run: |
          ls -l
          echo: pwd
      - name: Run pro.sh script
        run: bash pro.sh


      - name: Run pro.sh script
        run: bash pre.sh

      - name: Run pro.sh script
        run: bash dev.sh

   