name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pull-request-number:
        description: 'Pull request number'
        required: false
        default: '1'
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - development
          - preproduction
          - production

env:
  TF_VERSION: '1.0.0'
  TF_WORKING_DIR: ${{ github.event.inputs.environment == 'development' && 'dev' || github.event.inputs.environment == 'preproduction' && 'pre' || github.event.inputs.environment == 'production' && 'pro' }}

jobs:
  check_event:
    runs-on: ubuntu-latest
    steps:
      - name: Check if event is pull_request or pull-request-number is provided
        run: |
          if [[ "${{ github.event_name }}" != "pull_request" && -z "${{ github.event.inputs.pull-request-number }}" ]]; then
            echo "This action must be run using a pull_request event or have an explicit pull-request-number provided."
            exit 1
          fi

  manual_approval:
      name: 'Manual Approval'
      runs-on: ubuntu-latest
      needs: terraform
      steps:
        - name: Wait for approval
          uses: hmarr/auto-approve-action@v2
          with:
            github-token: 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



            
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest



    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run dev.sh script
        if: ${{ env.TF_WORKING_DIR == 'dev' }}
        run: bash dev.sh

      - name: Run pre.sh script
        if: ${{ env.TF_WORKING_DIR == 'pre' }}
        run: bash pre.sh

      - name: Run pro.sh script
        if: ${{ env.TF_WORKING_DIR == 'pro' }}
        run: bash pro.sh

  # reusable:
  #   needs: terraform
  #     # We do not need to check out the repository to use the reusable workflow
  #   uses: ./.github/workflows/reusable-workflow.yml
  #   with:
  #     reusable_input: "job-2-input"
  #     filename: "input.txt"
  #   # secrets:
  #   #   # Can also implicitly pass the secrets with: secrets: inherit
  #   #   HELLO_WORLD_SECRET: TERCES_DLROW_OLLEH          






  