name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - development
          - preproduction
          - production

env:
  TF_VERSION: '1.0.0'
  TF_WORKING_DIR: ${{ github.event.inputs.environment == 'development' && 'dev' || github.event.inputs.environment == 'preproduction' && 'pre' || github.event.inputs.environment == 'production' && 'pro' }}

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest



    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Run dev.sh script
        if: ${{ env.TF_WORKING_DIR == 'dev' }}
        run: bash dev.sh

      - name: Run pre.sh script
        if: ${{ env.TF_WORKING_DIR == 'pre' }}
        run: bash pre.sh

      - name: Run pro.sh script
        if: ${{ env.TF_WORKING_DIR == 'pro' }}
        run: bash pro.sh

  # reusable:
  #   needs: terraform
  #     # We do not need to check out the repository to use the reusable workflow
  #   uses: ./.github/workflows/reusable-workflow.yml
  #   with:
  #     reusable_input: "job-2-input"
  #     filename: "input.txt"
  #   # secrets:
  #   #   # Can also implicitly pass the secrets with: secrets: inherit
  #   #   HELLO_WORLD_SECRET: TERCES_DLROW_OLLEH


  manual_approval:
    name: 'Manual Approval'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Wait for approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: 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