name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - pre
          - pro

env:
  TF_VERSION: '1.0.0'
  TF_WORKING_DIR: '${{ github.event.inputs.environment }}'

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest



    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: directory
      #   run: |
      #     ls -l
          
      - name: List directory contents
        run: echo $(ls -l)

      - name: Run dev.sh script
        run: bash dev.sh

      # - name: Run pro.sh script
      #   run: bash pre.sh

      # - name: Run pro.sh script
      #   run: bash pro.sh

   