name: Dynamic Workflow Controller

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Recurso a procesar (e.g., recurso1)'
        required: true

jobs:
  generate-yaml:
    runs-on: ubuntu-latest
    outputs:
      yaml_content: ${{ steps.generate.outputs.yaml_content }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate dynamic YAML
        id: generate
        run: |
          # Genera un YAML basado en el input
          YAML_CONTENT=$(cat <<EOF
          jobs:
            process-${{ github.event.inputs.resource }}:
              runs-on: ubuntu-latest
              steps:
                - name: Process resource
                  run: echo "Processing ${{ github.event.inputs.resource }}"
                - name: Run custom logic
                  run: cd resources/${{ github.event.inputs.resource }} && bash ./deploy.sh
          EOF
          )
          # Escapa el contenido para que sea seguro como output
          echo "yaml_content<<EOF" >> $GITHUB_OUTPUT
          echo "$YAML_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  execute-dynamic:
    needs: generate-yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Execute dynamic logic
        env:
          YAML_CONTENT: ${{ needs.generate-yaml.outputs.yaml_content }}
        run: |
          # Aquí podrías parsear el YAML con una herramienta como yq
          echo "$YAML_CONTENT" > dynamic.yml
          # Extraer lógica específica, por ejemplo, ejecutar comandos
          RESOURCE='${{ github.event.inputs.resource }}'
          cd resources/$RESOURCE && bash ./deploy.sh