name: Dynamic Resource Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "jq version:"
          jq --version
          echo "Current directory:"
          pwd
          echo "Listing resources directory:"
          ls -l resources || echo "No resources directory"

      - name: List resource folders
        id: set-resources
        run: |
          # Initialize empty JSON array
          resources="[]"
          if [ -d "resources" ]; then
            mapfile -t dirs < <(find resources -maxdepth 1 -type d -not -path resources | xargs -n 1 basename 2>/dev/null)
            if [ ${#dirs[@]} -gt 0 ]; then
              resources=$(printf '%s\n' "${dirs[@]}" | jq -R . | jq -s .)
            fi
          fi
          # Validate JSON
          if echo "$resources" | jq . >/dev/null 2>&1; then
            echo "Generated JSON: $resources"
          else
            echo "Invalid JSON, falling back to empty array"
            resources="[]"
          fi
          echo "resources=$resources" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT contents:"
          cat $GITHUB_OUTPUT

  process-resources:
    needs: discover-resources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: ${{ fromJSON(needs.discover-resources.outputs.resources) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process resource
        run: |
          echo "Processing ${{ matrix.resource }}"
          if [ -d "resources/${{ matrix.resource }}" ]; then
            cd resources/${{ matrix.resource }}
            # Add your specific logic here, e.g., run a script
            echo "Running task for ${{ matrix.resource }}"
            # bash ./script.sh
            cd ../..
          else
            echo "Error: Directory resources/${{ matrix.resource }} not found"
            exit 1
          fi