name: Dynamic Resource Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List resource folders
        id: set-resources
        run: |
          if [ -d "resources" ]; then
            resources=$(find resources -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R . | jq -s .)
          else
            resources="[]"
          fi
          echo "resources=$resources" >> $GITHUB_OUTPUT

        