name: Dynamic Resource Workflow

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Recurso a procesar (e.g., recurso1)'
        required: true
        type: string

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List resource folders
        id: set-resources
        run: |
          resources="[]"
          if [ -d "resources" ]; then
            resources=$(find resources -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R . | jq -s .)
          fi
          echo "resources=$resources" >> $GITHUB_OUTPUT
          echo "Available resources: $resources"

  validate-input:
    needs: discover-resources
    runs-on: ubuntu-latest
    steps:
      - name: Validate selected resource
        run: |
          resources_list='${{ needs.discover-resources.outputs.resources }}'
          input_resource='${{ github.event.inputs.resource }}'
          if ! echo "$resources_list" | jq -e --arg res