name: Dynamic Deploy Terraform Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      resource:
        description: 'Recurso a ejecutar (dejar vacío para ejecutar todos)'
        required: false
        default: ''

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
  CONTAINER_NAME: tfstate
  ENVIRONMENTS: dev pre pro

permissions:
  contents: read
  id-token: write
  pull-requests: write
  actions: write

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List resource directories
        id: set-resources
        run: |
          # Lista las carpetas en el directorio raíz, excluyendo .git y otros ocultos
          resources=$(find . -maxdepth 1 -type d -not -path '.' -not -path './.*' -exec basename {} \; | jq -R . | jq -s -c .)
          if [ "$resources" = "[]" ]; then
            echo "Error: No resources found"
            exit 1
          fi
          echo "Found resources: $resources"
          # Validar input si se proporciona
          if [[ -n "${{ github.event.inputs.resource }}" ]]; then
            if ! echo "$resources" | jq -e '.[] | select(. == "${{ github.event.inputs.resource }}")'; then
              echo "Error: El recurso '${{ github.event.inputs.resource }}' no existe"
              exit 1
            fi
          fi
          # Escribir la salida en una sola línea
          echo "resources=$resources" >> $GITHUB_OUTPUT
        shell: bash

  deploy-resources:
    needs: discover-resources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: ${{ fromJson(needs.discover-resources.outputs.resources) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Run Terraform for resource
        if: ${{ github.event.inputs.resource == '' || github.event.inputs.resource == matrix.resource }}
        run: |
          echo "Ejecutando Terraform para ${{ matrix.resource }}"
          # Añade aquí los comandos específicos de Terraform para el recurso
          cd ${{ matrix.resource }}
          terraform init -backend-config="storage_account_name=$AZURE_STORAGE_ACCOUNT" \
                         -backend-config="container_name=$CONTAINER_NAME" \
                         -backend-config="key=${{ matrix.resource }}.tfstate" \
                         -backend-config="access_key=$AZURE_STORAGE_KEY"
          terraform plan
          terraform apply -auto-approve