name: Matriz con salidas

on:
  push:
    branches:
      - main

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      colors: ${{ steps.colors.outputs.colors }}
    steps:
      - name: Definir colores
        id: colors
        run: echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
    steps:
      - name: Generar artefacto
        env:
          color: ${{ matrix.color }}
        run: echo "$color" > color
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.color }}
          path: color

  consume-artifacts:
    needs: produce-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.color }}
      - name: Mostrar contenido
        run: cat color