name: Dynamic Resource Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "jq version:"
          jq --version
          echo "Current directory:"
          pwd
          echo "Listing resources directory:"
          ls -l resources || echo "No resources directory"

      - name: List resource folders
        id: set-resources
        run: |
          # Initialize empty JSON