name: Generate and Deploy Terraform Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  git_token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discover resources and generate workflow
        id: generate
        run: |
          # Descubrir recursos
          RESOURCES=$(find . -maxdepth 1 -type d -not -path '.' -not -path './.*' -exec basename {} \;)
          
          # Crear el YAML dinámico
          cat << 'EOF' > .github/workflows/dynamic-deploy.yml
          name: Dynamic Deploy Terraform Resources

          on:
            workflow_call:

          env:

            ENVIRONMENTS: dev pre pro

          jobs:
          EOF

          # Añadir un job por cada recurso
          for RESOURCE in $RESOURCES; do
            cat << EOF >> .github/workflows/dynamic-deploy.yml
            $RESOURCE:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout repository
                  uses: actions/checkout@v4


                - name: Deploy Terraform for $RESOURCE
                  env:

                  run: |
                    for ENV in \$ENVIRONMENTS; do
                      echo "Deploying $RESOURCE in \$ENV..."
                      cd "$RESOURCE/\$ENV"

                    done
          EOF
          done

      - name: Commit and push generated workflow
        run: |
          git config user.name "jmorenocastillo"
          git config user.email "c_ompucenter@yahoo.es"
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
          git add .github/workflows/dynamic-deploy.yml
          git commit -m "Generate dynamic workflow for resources"
          username=$(git config user.name)
          password=secrets.git_token
          git push

      - name: Trigger dynamic workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'dynamic-deploy.yml',
              ref: 'main'
            });