name: Generate and Deploy Terraform Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Discover resources and generate workflow
        id: generate
        run: |
          # Descubrir recursos
          RESOURCES=$(find . -maxdepth 1 -type d -not -path '.' -not -path './.*' -exec basename {} \;)
          echo "Resources found: $RESOURCES"
          
          # Verificar que RESOURCES no esté vacío
          if [ -z "$RESOURCES" ]; then
            echo "Error: No resources found"
            exit 1
          fi

          # Crear el YAML dinámico
          mkdir -p .github/workflows
          cat << 'EOF' > .github/workflows/dynamic-deploy.yml
          name: Dynamic Deploy Terraform Resources
          EOF

         

      - name: Debug generated workflow
        run: |
          echo "Generated workflow content:"
          cat .github/workflows/dynamic-deploy.yml || echo "Error: Failed to read dynamic-deploy.yml"

      - name: Upload generated workflow as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-workflow
          path: .github/workflows/dynamic-deploy.yml

      - name: Commit and push generated workflow
        run: |
          git config user.name jmorenocastillo"
          git config user.email "c_ompucenter@yahoo.es"
          git config --global user.password ${{ secrets.git_token }}
          git add dynamic-deploy.yml
          password= ${{ secrets.git_token }}
          # Verificar si hay cambios para evitar commits innecesarios
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate dynamic workflow for resources [skip ci]"
            git push
          fi

      - name: Trigger dynamic workflow
        if: steps.commit.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'dynamic-deploy.yml',
              ref: 'main'
            });