name: Dynamic Resource Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.set-resources.outputs.resources }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List resource folders
        id: set-resources
        run: |
          # Ensure resources directory exists
          if [ ! -d "resources" ]; then
            echo "No resources directory found, setting empty list"
            echo "resources=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          # List directories in resources/ and convert to JSON array
          # Use find to avoid ls issues with empty directories
          resources=$(find resources -maxdepth 1 -type d -not -path resources | xargs -n 1 basename 2>/dev/null | jq -R . | jq -s .)
          
          # Validate JSON output
          if echo "$resources" | jq . >/dev/null 2>&1; then
            echo "Valid JSON: $resources"
            echo "resources=$resources" >> $GITHUB_OUTPUT
          else
            echo "Invalid JSON generated, setting empty list"
            echo "resources=[]" >> $GITHUB_OUTPUT
          fi

          # Debug: Print the final output for verification
          echo "Output written to GITHUB_OUTPUT: $(cat $GITHUB_OUTPUT)"

  process-resources:
    needs: discover-resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process resources
        run: |
          # Get the resources JSON array
          resources='${{ needs.discover-resources.outputs.resources }}'
          echo "Received resources: $resources"

          # Validate JSON
          if ! echo "$resources" | jq . >/dev/null 2>&1; then
            echo "