# name: Manual Approval Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Running some script"

  approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Approval step
      id: approval
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: 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
      
    - name: Wait for approval
      if: success()
      run: echo "Waiting for approval"