name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: "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"
          approvers: jmorenocastillo
      - name: Deploy to production
        run: echo deploying