name: Run with reusable workflow

on:
  workflow_dispatch: # Manually trigger the workflow

    inputs:
      environment:
        type: string  

jobs:
  jobid:
    runs-on: ubuntu-latest
    env:
      client_id: ${{ vars[format('client_id_{0}', inputs.environment)] }}
    steps:
    - run: |
        echo "valor ${{ env.client_id }}"