name: Run with reusable workflow

on:
  workflow_dispatch: # Manually trigger the workflow

    inputs:
      dockerfile:
        type: string  

jobs:
  jobid:
    runs-on: ubuntu-latest
    env:
      BUILD_SECRETS: ${{ vars[format('{0}_BUILD_SECRETS', inputs.dockerfile)] }}
      client_id: ${{ vars[format('client_id_{0}', inputs.dockerfile)] }}
    steps:
    - run: echo "$BUILD_SECRETS"