name: Reusable steps (AKA composite action)
description: Demonstrate how to use reusable steps in a workflow
# Schema: https://json.schemastore.org/github-action.json

# Runs on the same runner and same work area as the main workflow.
# No need to use 'build artifacts' to share files with the main workflow.
# Env variables are inherited.
# Secrets are not available -- must be passed explicitly as inputs or env vars.

inputs:
  reusable_input:
    description: 'Input to the reusable workflow'
    required: true
  filename:
    required: true
outputs:
  # Map the action output(s) to step output(s)
  reusable_output:
    description: 'Output from the reusable workflow'
    value: ${{ steps.process-step.outputs.step_output }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
        uses: actions/checkout@v4

      - name: get job name
        id: get_job_name
        run: echo "${{ github.job }}"

      - name: working directory
        run: pwd
